{% set name = "atlasclient" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6de733df822891b59e35ea71adac750b926e670c520eb31eb3f3a43d1f52f97

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"

requirements:
  host:
    - python
    - pip >=18.1
    - six >=1.11.0
    - click >=6.0
    - requests >=2.18.4
  run:
    - six
    - click
    - requests

test:
  imports:
    - atlasclient
    - atlasclient.base
    - atlasclient.client
    - atlasclient.events
    - atlasclient.exceptions
    - atlasclient.models
    - atlasclient.utils

about:
  home: https://github.com/jpoullet2000/atlasclient
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Apache Atlas client in Python'
  description: |
    **Apache Atlas client in Python**

    Only compatible with Apache Atlas REST API v2.

    Free software: Apache Software License 2.0
    [Documentation](https://atlasclient.readthedocs.io)

    **Features**

    Lazy loading: requests are only performed when data are required and not yet available
    Resource object relationships: REST API from sub-resources are done transparently for the user,
    for instance the user does not have to know that it needs to trigger a different REST
    request for getting the classifications of a specific entity.

  doc_url: https://atlasclient.readthedocs.io/
  dev_url: https://github.com/jpoullet2000/atlasclient

extra:
  recipe-maintainers:
    - BrentDorsey
